### ISSUE TITLE
Get Basic UI Styling

### ISSUE THREAD

**Issue by CleverOscar** [CleverOscar/React_Calculator#1]
Getting the basic Calculator component up is required.

Please keep in mind that we would like to make this calculator reusable so please try to code-split necessary elements only.

As we will need two different views for our operations

**Comment by Nizarahammed** [comment]
Hi @CleverOscar , I am willing to work on this issue. Can you assign it to me?

**Comment by CleverOscar** [comment]
Hello there @Nizarahammed, I'll go ahead and assign this issue to you, thank you in advance.

**Comment by CleverOscar** [comment]
Hey @Nizarahammed checking in if this has already been worked on.

**Comment by CleverOscar** [comment]
https://github.com/CleverOscar/React_Calculator/pull/4 Updated UI
